[target.thumbv7em-none-eabihf]
runner = 'probe-rs run --chip nrf52840_xxAA'
rustflags = [
  "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf" # Cortex-M4F and Cortex-M7F (with FPU)

[env]
DEFMT_LOG = "info"
